version: '3.3'

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
       - MYSQL_ROOT_PASSWORD
    volumes:
       - db-data:/var/lib/mysql
    networks:
       - rm

  pma:
      image: hauptmedia/phpmyadmin:latest
      environment:
        - PMA_ABSOLUTE_URI
        - SERVER_1_HOST=db
      ports:
        - 8070:80
      networks:
        - rm

networks:
  rm:
    driver: overlay

volumes:
  db-data:
